### ISSUE TITLE
which topic could be showed on rviz?

### ISSUE THREAD

**Issue by YiChenCityU** [KumarRobotics/msckf_vio#4]
I have run the code with rviz. But I can only show the images, and cannot subscribe odometry or some thing else. What's wrong? 
Thanks very much.

**Comment by ke-sun** [comment]
The odometry topic should be `/$(arg robot)/vio/odom`.
Could you provide more details like which launch file and rviz configuration file you are using. Which dataset are you testing on? Is there any runtime error?

**Comment by SkyRiderMike** [comment]
I don't know how to run this algorithm, could you please provide more details of command for running this code ?

**Comment by YiChenCityU** [comment]
Hi,
I run like this:
roslaunch /home/eason/msckf_ws/src/msckf_vio/launch/msckf_vio_euroc.launch 
rosbag play /home/eason/Documents/data/MH_01_easy.bag

Rviz like this picture: 
[rviz](https://www.dropbox.com/s/5jx8i7na53ko4h1/Screenshot%20from%202018-01-10%2010%3A54%3A27.png?dl=0) 
[terminal](https://www.dropbox.com/s/epi9u5ixku1csos/Screenshot%20from%202018-01-10%2010%3A54%3A50.png?dl=0)

**Comment by YacongWang** [comment]
@YiChenCityU Can you save the results about timestamp, position, and orientation? And the rviz don't plot the route just like VINS-mono. I think we have more to do to run this repo properly.

**Comment by pxlong** [comment]
@YacongWang I agree. I have recorded a video on euroc dataset (#6), maybe I miss some key-steps to run this repo correctly. 

**Update**:
After compiling the code in the **Release** mode, it works very well. 
Cheers.

**Comment by edgar-explorer** [comment]
@ke-sun Can it output dataset trajectory like ORB-SLAM or vins-mono.

**Comment by ke-sun** [comment]
@YiChenCityU 

There are some tips that may be helpful for you.

1. Make sure the software is compiled in release mode.
2. There are rviz configuration files in the rviz folder. It may be convenient to use them directly.
3. The filter requires the robot to stay static at first in order to collect a couple of IMU messages to initialize gyro bias, acc bias and most importantly, the initial orientation. For EuRoC `MH_01_easy` and `MH_02_easy`, the datasets start directly with the robot in motion. Therefore, the filter does not work well with those two datasets. Also for the other datasets, I suggest that you could launch the software first and then start to play the bagfiles, which allows the filter to catch the first few static IMU messages.

Hope that helps solve your problem.

**Comment by ke-sun** [comment]
@cumtchenchang 
@YacongWang 

It does not output `nav_msgs/Path` as a topic. One possible quick way to visualize a "trajectory" is to accumulate the odometry messages in rviz.

**Comment by YacongWang** [comment]
I have added the ```nav_msgs/Path``` in the Publish function, and the ```echo topic``` is
```
---
header: 
  seq: 430
  stamp: 
    secs: 1403638540
    nsecs: 577829500
  frame_id: "world"
poses: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1403638540
        nsecs: 577829500
      frame_id: "world"
    pose: 
      position: 
        x: -0.441163233876
        y: 0.0728935733359
        z: 0.202584217
      orientation: 
        x: -0.0474131629629
        y: -0.823935342842
        z: -0.0416467497592
        w: 0.563159028187
---
```
But in the rviz, there isn't route. And the output is attached below. Is there anything wrong?
![image](https://user-images.githubusercontent.com/22884185/35044354-0a2f1ccc-fbcb-11e7-949f-68efccf23dbe.png)
